server:
  port: 8001
#  ssl:
#    key-store: classpath:xiaochengxu.p12.pfx
#    key-store-password: 123456
#    key-store-type: PKCS12
#    key-alias: tomcat
#/home/test/
mybatis:
  config-location: classpath:mybatis/mybatis.cfg.xml        # mybatis配置文件所在路径
  type-aliases-package: com.yuhan.entities    # 所有Entity别名类所在包
  mapper-locations:
  - classpath:mybatis/mapper/**/*.xml                       # mapper映射文件

spring:
 #  main:
 #   web-environment: false
   application:
    name: microservicecloud-dept
   datasource:
    type: com.alibaba.druid.pool.DruidDataSource            # 当前数据源操作类型
    driver-class-name: org.gjt.mm.mysql.Driver              # mysql驱动包
    url: jdbc:mysql://49.234.133.200:3306/weixin          # 数据库名称
    username: root
    password: YUHAN@54xurujie
    #YUHAN@54XUrujie
    dbcp2:
      min-idle: 5                                           # 数据库连接池的最小维持连接数
      initial-size: 5                                       # 初始化连接数
      max-total: 5                                          # 最大连接数
      max-wait-millis: 200                                  # 等待连接获取的最大超时时间
eureka:
   client:
      register-with-eureka: false
      fetch-registry: false

#server.ssl.protocol=TLSv1.1
#eureka:
 # client: #客户端注册进eureka服务列表内
 #    service-url:
      #defaultZone: http://localhost:7001/eureka
 #      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/
 # instance:
 #   instance-id: weixin-dept8001
 #   prefer-ip-address: true     #访问路径可以显示IP地址

#info:
#  app.name: atguigu-microservicecloud
#  company.name: www.atguigu.com
#  build.artifactId: $project.artifactId$
#  build.version: $project.version$

